import { authMiddleware } from '@clerk/nextjs/server'

export default authMiddleware({
  publicRoutes: [
    '/',
    '/about(.*)',
    '/events(.*)',
    '/news(.*)',
    '/blog(.*)',
    '/gallery(.*)',
    '/contact(.*)',
    '/get-started(.*)',
    '/newsletter(.*)',
    '/privacy(.*)',
    '/terms(.*)',
    '/sign-in(.*)',
    '/sign-up(.*)',
    '/faq(.*)',
    '/sponsorship(.*)',
    '/projects(.*)',
    '/studio(.*)',
    '/market(.*)',
    '/hire(.*)',
    '/launch(.*)',
    '/creators(.*)',
    '/payment(.*)',
    '/admin(.*)',
    '/api/news(.*)',
    '/api/blog(.*)',
    '/api/events(.*)',
    '/api/gallery(.*)',
    '/api/leadership(.*)',
    '/api/partners(.*)',
    '/api/projects(.*)',
    '/api/stats(.*)',
    '/api/search(.*)',
    '/api/contact(.*)',
    '/api/project-inquiry(.*)',
    '/api/newsletter(.*)',
    '/api/upload(.*)',
    '/api/studio/templates(.*)',
    '/api/market/products(.*)',
    '/api/hire(.*)',
    '/api/creators(.*)',
    '/api/payments/ipn(.*)',
    '/api/generate-business-case(.*)',
    '/api/actions/proposal(.*)',
    '/api/notifications(.*)',
    '/api/referrals(.*)',
    '/api/marketing/newsletter(.*)',
    '/api/marketing/sms-blast(.*)',
    '/api/marketing/push-blast(.*)',
    '/api/partners(.*)',
    '/api/service-requests(.*)',
    '/notifications(.*)',
  ],
})

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}
